#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=8

banner "raincheck cloud capture runner — always-on box (ticket 19)"

# ── Stage 1: preflight + provider pick ────────────────────────────────────
stage "Preflight + provider pick"
say "This wizard puts the archiver's capture loop on a small always-on Linux box:"
say "systemd + python3 + aws cli, hourly push to the existing R2 bucket, daily"
say "gap check. Run it from the raincheck repo root on the Mac."
[[ -f systemd/raincheck-archiver.service && -f scripts/box-coldpush.sh ]] \
  || { warn "run me from the raincheck repo root (systemd/ and scripts/ not found)"; exit 1; }
for k in RAINCHECK_COLD_BUCKET RAINCHECK_COLD_ENDPOINT RAINCHECK_COLD_KEY_ID RAINCHECK_COLD_SECRET; do
  [[ -n "$(_existing "$k" || true)" ]] \
    || { warn "$k missing from .env — run scripts/cold-storage-wizard.sh first"; exit 1; }
done
say ""
say "Provider: Oracle Always-Free ARM (\$0/month, signup + capacity friction) or"
say "Hetzner CAX11 (~EUR 3.3/month, boring and reliable). The runner is identical"
say "on both — plain systemd; switching later is one re-run of this wizard."
if confirm "Try Oracle Always-Free first (n = Hetzner)?"; then PROVIDER=oracle; else PROVIDER=hetzner; fi
write_env RAINCHECK_BOX_PROVIDER "$PROVIDER"

# ── Stage 2: ssh key ──────────────────────────────────────────────────────
stage "SSH key"
ask KEYFILE "SSH private key to use [~/.ssh/id_ed25519]:"
[[ -z "$KEYFILE" ]] && KEYFILE="$HOME/.ssh/id_ed25519"
KEYFILE="${KEYFILE/#\~/$HOME}"
if [[ ! -f "$KEYFILE" ]]; then
  say "No key at $KEYFILE — generating one (no passphrase, for this box only)."
  ssh-keygen -t ed25519 -N "" -f "$KEYFILE" -C raincheck-box
fi
write_env RAINCHECK_BOX_SSH_KEY "$KEYFILE"
say ""
say "Public key to paste into the provider console in the next stage:"
printf '\n  %s\n\n' "$(cat "$KEYFILE.pub")"
pause "Copied it? Press Enter."

# ── Stage 3: provider account + VM ────────────────────────────────────────
if [[ "$PROVIDER" == oracle ]]; then
  stage "Oracle Cloud account + Always-Free ARM instance"
  open_url "https://signup.cloud.oracle.com/"
  step "Create the free account (card needed for identity; Always Free stays \$0)."
  step "Console → Compute → Instances → Create instance."
  step "Image: Ubuntu 24.04 (aarch64). Shape: VM.Standard.A1.Flex, 1 OCPU / 6 GB"
  say "  (Always-Free allows up to 4 OCPU / 24 GB; a poller needs far less)."
  step "Networking: defaults are fine (public IP, ssh 22 already open; the box"
  say "  only needs OUTBOUND https)."
  step "Add SSH key: paste the public key from the previous stage."
  step "Create, wait for RUNNING, copy the public IP."
  warn "'Out of capacity' on A1.Flex is common: retry later, try another AD, or"
  say "  re-run this wizard and answer n for the Hetzner path."
  note "Default login user on Oracle Ubuntu images: ubuntu"
else
  stage "Hetzner account + CAX11"
  open_url "https://console.hetzner.com/"
  step "Create the account, then a project → Add Server."
  step "Location: Falkenstein or Helsinki (ARM CAX servers are EU-only; latency is"
  say "  irrelevant for a 30s poller). Image: Ubuntu 24.04."
  step "Type: Arm64 → CAX11 (2 vCPU / 4 GB / 40 GB, ~EUR 3.3/month)."
  step "SSH key: add the public key from the previous stage."
  step "Create & buy now, copy the public IPv4."
  note "Default login user on Hetzner images: root"
fi

# ── Stage 4: reach the box ────────────────────────────────────────────────
stage "Reach the box"
ask BOX_HOST "Box public IP:"
DEFAULT_USER=ubuntu; [[ "$PROVIDER" == hetzner ]] && DEFAULT_USER=root
ask BOX_USER "SSH login user [$DEFAULT_USER]:"
[[ -z "$BOX_USER" ]] && BOX_USER="$DEFAULT_USER"
SSH_OPTS=(-i "$KEYFILE" -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
until sshout=$(ssh "${SSH_OPTS[@]}" "$BOX_USER@$BOX_HOST" true 2>&1); do
  warn "cannot ssh $BOX_USER@$BOX_HOST with $KEYFILE — check IP, user, key, firewall"
  if [[ -n "$sshout" ]]; then note "ssh said: $(printf '%s' "$sshout" | tail -n 3)"; fi
  pause "Fix it, then press Enter to retry."
done
printf '  %s✓ ssh works%s — %s@%s\n' "$GREEN" "$RESET" "$BOX_USER" "$BOX_HOST"
write_env RAINCHECK_BOX_HOST "$BOX_HOST"
write_env RAINCHECK_BOX_USER "$BOX_USER"
run() { ssh "${SSH_OPTS[@]}" "$BOX_USER@$BOX_HOST" "$@"; }

# ── Stage 5: runtime + code on the box ────────────────────────────────────
stage "Install runtime + code (automated, ~2 min)"
say "apt python3-venv, /opt/raincheck layout, venv with pyarrow/requests/"
say "gtfs-realtime-bindings/confluent-kafka/awscli, service user 'raincheck'..."
note "(apt waits up to 5 min if cloud-init still holds the package lock on a fresh VM)"
run 'sudo apt-get -o DPkg::Lock::Timeout=300 update -qq &&
     sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=300 install -y -qq python3-venv'
run 'sudo useradd -r -d /opt/raincheck -s /usr/sbin/nologin raincheck 2>/dev/null || true'
run "sudo mkdir -p /opt/raincheck && sudo chown \$USER /opt/raincheck"
# tar over the existing ssh channel: no rsync on either end, no -e quoting hazards
COPYFILE_DISABLE=1 tar -cf - src/raincheck scripts/box-coldpush.sh scripts/coldgaps.sh systemd \
  | run 'tar -C /opt/raincheck -xf -'
run 'chmod +x /opt/raincheck/scripts/*.sh
     sudo install -d -o raincheck -g raincheck /opt/raincheck/data
     test -x /opt/raincheck/venv/bin/pip || python3 -m venv /opt/raincheck/venv
     /opt/raincheck/venv/bin/pip install -q --upgrade pip
     /opt/raincheck/venv/bin/pip install -q pyarrow requests gtfs-realtime-bindings confluent-kafka awscli'
printf '  %s✓ box ready%s\n' "$GREEN" "$RESET"

# ── Stage 6: /etc/raincheck.env ───────────────────────────────────────────
stage "Write /etc/raincheck.env on the box"
say "R2 credentials come from the local .env; the box keeps them in root-owned"
say "/etc/raincheck.env (600), read by the systemd units only."
ask BRONZE_GB "Box disk cap RAINCHECK_BRONZE_GB [20]:"
[[ -z "$BRONZE_GB" ]] && BRONZE_GB=20
printf 'RAINCHECK_ARCHIVE_ROOT=/opt/raincheck/data\nRAINCHECK_BRONZE_GB=%s\nRAINCHECK_COLD_BUCKET=%s\nRAINCHECK_COLD_ENDPOINT=%s\nRAINCHECK_COLD_KEY_ID=%s\nRAINCHECK_COLD_SECRET=%s\n' \
  "$BRONZE_GB" "$(_existing RAINCHECK_COLD_BUCKET)" "$(_existing RAINCHECK_COLD_ENDPOINT)" \
  "$(_existing RAINCHECK_COLD_KEY_ID)" "$(_existing RAINCHECK_COLD_SECRET)" \
  | run "sudo sh -c 'umask 077; cat > /etc/raincheck.env; chmod 600 /etc/raincheck.env'"
printf '  %s✓ wrote%s /etc/raincheck.env (root, 600)\n' "$GREEN" "$RESET"

# ── Stage 7: services on ──────────────────────────────────────────────────
stage "Install + start the services"
run 'sudo cp /opt/raincheck/systemd/raincheck-archiver.service \
        /opt/raincheck/systemd/raincheck-coldpush.service /opt/raincheck/systemd/raincheck-coldpush.timer \
        /opt/raincheck/systemd/raincheck-coldgaps.service /opt/raincheck/systemd/raincheck-coldgaps.timer \
        /etc/systemd/system/
     sudo systemctl daemon-reload
     sudo systemctl enable --now raincheck-archiver.service raincheck-coldpush.timer raincheck-coldgaps.timer'
say "Waiting 45s for the first polls to land..."
sleep 45
if run 'systemctl is-active --quiet raincheck-archiver.service'; then
  printf '  %s✓ archiver active%s\n' "$GREEN" "$RESET"
  run 'sudo journalctl -u raincheck-archiver -n 6 --no-pager' || true
else
  warn "archiver not active — on the box: sudo journalctl -u raincheck-archiver -n 30"
  SKIPPED+=("archiver active check (stage 7)")
fi
pause "Continue? Press Enter."

# ── Stage 8: first push + what happens next ───────────────────────────────
stage "First push + cutover plan"
say "Pushing the first captured parts to R2 (raincheck-coldpush.service)..."
if run 'sudo systemctl start raincheck-coldpush.service && sudo journalctl -u raincheck-coldpush -n 6 --no-pager'; then
  printf '  %s✓ first push OK%s — the box now captures and ships on its own\n' "$GREEN" "$RESET"
else
  warn "first push failed — journalctl -u raincheck-coldpush on the box; re-run this stage"
  SKIPPED+=("first push verify (systemctl start raincheck-coldpush.service)")
fi
say ""
say "From here:"
note "- hourly: box pushes + prunes verified parts (raincheck-coldpush.timer)"
note "- daily 02:15 UTC: coldgaps checks 24 hour-dirs per kind (raincheck-coldgaps.timer);"
note "  same check from the Mac: make coldgaps [DATE=YYYY-MM-DD]"
note "- box health at a glance: ssh in, systemctl --failed. One blind spot: the"
note "  archiver's over-budget stop exits CLEAN (STOPPED_BUDGET marker) — it shows"
note "  up as the next day's coldgaps failure, not as a failed archiver unit"
note "- while BOTH the Mac and box capture, Mac 'make coldcheck' may flag size"
note "  mismatches on windows the box also pushed — overlap, not data loss"
note "- after 7 clean days of coldgaps: record the cutover note on ticket 19 and"
note "  optionally retire the Mac agent: launchctl bootout gui/\$(id -u)/com.raincheck.archiver"

finish
